NUMBER_OF_PATHS = 100
NUMBER_OF_STEPS = 365
CONFIDENCE_INTERVAL = 0.95
TIME_TO_MATURITY = 1
USE_ANTITHETIC_VARIATES = True
PATH_RANDOM_SEED = 42  # Set None not to fix seed
OPTIONS_PARAMS_RANDOM_SEED = 234  # Set None not to fix seed
USE_DATA_FROM_FILE = True
DATASET_SIZE = 100000  # Used only when USE_DATA_FROM_FILE = False
EPOCHS_COUNT = 80
